DATE_FORMAT = "%d.%m.%Y"

COMMANDS_INFO = {
    "hello": "Greets the user",
    "add": "Add a new contact",
    "change": "Change an existing phone",
    "phone": "Show phone(s) of a contact",
    "all": "Show all contacts",
    "delete": "Delete a contact",
    "search": "Search contacts by keyword",
    "add-email": "Add an email to a contact",
    "add-birthday": "Add a birthday date",
    "show-birthday": "Show birthday for a contact",
    "birthdays": "Show upcoming birthdays",
    "add-address": "Add an address to a contact",
    "delete-address": "Delete address from a contact",
    "find-city": "Find contacts by city",
    "search-address": "Search addresses by keyword",
    "show-addresses": "Show all addresses",
    "add-note": "Add a new note",
    "show-notes": "Show all notes",
    "find-note": "Find notes by title",
    "edit-note": "Edit a note",
    "delete-note": "Delete a note",
    "add-tag": "Add a tag to a note",
    "find-tag": "Find notes by tag",
    "exit": "Exit the assistant",
    "close": "Exit the assistant",
}
