DATE_FORMAT = "%d.%m.%Y"

COMMANDS_INFO = {
    "hello": "Greets the user",
    "help": "Shows all available commands",
    "add [name]": "Add a new contact",
    "find [name]": "Find contact by name",
    "change [name] [old_phone] [new_phone]": "Change an existing phone",
    "phone [name]": "Show phone(s) of a contact",
    "search-phone [phone]": "Search contacts by phone number.",
    "all": "Show all contacts",
    "delete [name]": "Delete a contact",
    "search [keyword]": "Search contacts by keyword",
    "add-email [name] [email/new_email]": "Add/change an email to a contact",
    "add-birthday [name] [DD.MM.YYYY]": "Add/change a birthday date",
    "show-birthday [name]": "Show birthday for a contact",
    "birthdays [days]": "Show birthdays in the next N days (default: 7)",
    "add-address [name]": "Add an address to a contact",
    "delete-address [name]": "Delete address from a contact",
    "find-city [city]": "Find contacts by city",
    "search-address [query]": "Search addresses by query",
    "show-addresses": "Show all addresses",
    "add-note": "Add a new note",
    "show-notes": "Show all notes",
    "find-note": "Find notes by title",
    "edit-note": "Edit a note",
    "delete-note": "Delete a note",
    "add-tag": "Add a tag to a note",
    "find-tag [tag]": "Find notes by tag",
    "exit": "Exit the assistant",
    "close": "Exit the assistant",
}
